# Generated by Django 3.0.2 on 2020-02-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.ManyToManyField(to='specializations.Specialization'),
        ),
    ]
