# Generated by Django 3.0.2 on 2020-01-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Last Name'),
        ),
    ]
