# Generated by Django 3.0.2 on 2020-02-07 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '0002_auto_20200204_0740'),
        ('users', '0006_auto_20200204_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='specialization',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='specializations.Specialization'),
            preserve_default=False,
        ),
    ]
