# Generated by Django 3.0.2 on 2020-02-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200217_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='Mobile Number'),
        ),
    ]
