# Generated by Django 3.0.2 on 2020-02-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
