# Generated by Django 3.0.2 on 2020-02-13 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20200203_0538'),
        ('hospital', '0007_auto_20200210_1020'),
        ('specializations', '0002_auto_20200204_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('time_slot', models.DateTimeField()),
                ('notes', models.TextField(null=True)),
                ('at_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hospital.Hospital')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
                ('with_specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='specializations.Specialization')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.basemodel',),
        ),
    ]
