# Generated by Django 3.0.2 on 2020-03-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('appointment_status', models.CharField(choices=[('pending', 'Pending'), ('noshow', 'Patient did not show up'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('time_slot', models.DateTimeField()),
                ('notes', models.TextField(null=True)),
                ('feedback_given', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.basemodel',),
        ),
    ]
