# Generated by Django 3.0.2 on 2020-03-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='at_hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hospital.Hospital'),
        ),
    ]
