# Generated by Django 3.0.2 on 2020-03-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='feedback_given',
            field=models.BooleanField(default=False),
        ),
    ]
