# Generated by Django 3.0.2 on 2020-03-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20200305_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='display_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
