# Generated by Django 3.0.2 on 2020-02-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20200131_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.DateTimeField(),
        ),
    ]
