# Generated by Django 3.0.2 on 2020-03-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_display_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.DateTimeField(unique=True),
        ),
    ]
