# Generated by Django 3.0.2 on 2020-03-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20200309_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.DateTimeField(),
        ),
    ]
