# Generated by Django 3.0.2 on 2020-03-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('title', models.CharField(max_length=200)),
                ('url', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('app.basemodel',),
        ),
    ]
