# Generated by Django 3.0.2 on 2020-02-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
