# Generated by Django 3.0.2 on 2020-01-31 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('session_duration', models.IntegerField(verbose_name='Treatment session (in minutes)')),
                ('opening_hours', models.TimeField()),
                ('closing_hours', models.TimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.basemodel',),
        ),
    ]
