# Generated by Django 3.0.2 on 2020-02-04 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0002_auto_20200131_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'doctor'}, related_name='doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='admin',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
