# Generated by Django 3.0.2 on 2020-02-04 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0003_auto_20200204_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'doctor'}, related_name='doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
