# Generated by Django 3.0.2 on 2020-02-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_hospital_working_on_weekend'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='other_holidays',
            field=models.TextField(blank=True, null=True),
        ),
    ]
